# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Test Artifact

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup executable permission
      run: |
        chmod +x gradlew
        chmod +x gradle/wrapper/gradle-wrapper.jar
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Read gradle.properties
      uses: BrycensRanch/read-properties-action@v1
      id: properties
      with:
        file: gradle.properties
        all: true
    
    - name: Build with Gradle
      run: gradle build --info

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        # Artifact name
        name: ${{ steps.properties.outputs.publish_to_maven }}-${{ env.COMMIT_SHORT_SHA }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
          
